// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptiGo.Infrastructure.Persistence;

#nullable disable

namespace OptiGo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptiGoDbContext))]
    [Migration("20260418143918_AddPickupRequestsAndRoutePreview")]
    partial class AddPickupRequestsAndRoutePreview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptiGo.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<double>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("MobilityRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SelfTravel")
                        .HasColumnName("mobility_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transport_mode");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_members_session");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcceptedDriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_driver_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid")
                        .HasColumnName("passenger_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedDriverId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SessionId", "PassengerId")
                        .HasDatabaseName("idx_pickup_requests_session_passenger");

                    b.ToTable("pickup_requests", (string)null);
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DepartureLockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_locked_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FinalRouteSnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("final_route_snapshot_json");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("host_name");

                    b.Property<string>("LatestOptimizationSnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("latest_optimization_snapshot_json");

                    b.PrimitiveCollection<string[]>("NominatedVenueIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("nominated_venue_ids");

                    b.Property<string>("QueryText")
                        .HasColumnType("text")
                        .HasColumnName("query_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("WinningVenueId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("winning_venue_id");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Venue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<double>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PriceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("price_level");

                    b.Property<double>("Rating")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_venues_category");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("VenueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("idx_votes_session_member");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Member", b =>
                {
                    b.HasOne("OptiGo.Domain.Entities.Session", "Session")
                        .WithMany("Members")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.PickupRequest", b =>
                {
                    b.HasOne("OptiGo.Domain.Entities.Member", "AcceptedDriver")
                        .WithMany()
                        .HasForeignKey("AcceptedDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OptiGo.Domain.Entities.Member", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiGo.Domain.Entities.Session", "Session")
                        .WithMany("PickupRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedDriver");

                    b.Navigation("Passenger");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Vote", b =>
                {
                    b.HasOne("OptiGo.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptiGo.Domain.Entities.Session", "Session")
                        .WithMany("Votes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("OptiGo.Domain.Entities.Session", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PickupRequests");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
